### ISSUE TITLE
The train/val txt files for experiments.

### ISSUE THREAD

**Issue by Zxl19990529** [panzhiyi/URSS#1]
Thanks for your work. I wonder how do you use the scribble annotations of ScribbleSup, I didn't find the train/val txt files in their project homepage. Can you share it with me?

**Comment by panzhiyi** [comment]
ScribbleSup follows the setup of Pascal VOC 2012 and contains 10,582 training images & 1,449 validation images. Now, you can find the corresponding .txt file from the '\data\' path of this project.

> Thanks for your work. I wonder how do you use the scribble annotations of ScribbleSup, I didn't find the train/val txt files in their project homepage. Can you share it with me?
