### ISSUE TITLE
Difference between the validate codes in evaluate.py and train*.py files

### ISSUE THREAD

**Issue by Zxl19990529** [panzhiyi/URSS#2]
Hi, thanks for your work. I can run the training codes successfully. I noticed that the way of processing the network's predicts is different in evaluate.py and  training files. In evaluate.py, it has to go through the ```net_process``` and ```scale_process``` functions, and it runs slowly.
However, in training codes, it does not and runs more faster. What if I use the ```validate_tnt``` in training codes to reproduce the results? Will that result in something unexpected ?

**Comment by panzhiyi** [comment]
Thanks for your interest in our work. In the evaluate.py, we used the general tricks of multi-scale and flipping the input image horizontally to obtain better prediction results at the cost of slow speed. During the training process, only the center-cropped images at a single scale are validated to obtain faster validation speed. So, reproducing by the 'validate_tnt' function will give incomplete image output. If you want to evaluate at a single scale, you can replace the 193 lines in the evaluate.py with the following code:

`test(args, val_loader, model, args.numclasses, mean, std, 512, 465, 465, [1.0])`

**Comment by Zxl19990529** [comment]
Thanks very much, that helps a lot. One more question: I got two checkpoints after training, "model_best.pth.tar" and "checkpoint.pth.tar", which one should I use to reproduce the results in the paper? And can you release the pretrained model ?

**Comment by panzhiyi** [comment]
The "model_best.pth.tar" can reproduce the results. Here is the [link](https://drive.google.com/drive/folders/1szV-hehYfPtpS_BOfVwbODpsxAyrgJKy?usp=share_link) of pretrained models.

**Comment by Zxl19990529** [comment]
Thanks you very much! That helps me a lot.
