### ISSUE TITLE
The thickness of the lines.

### ISSUE THREAD

**Issue by Zxl19990529** [panzhiyi/URSS#3]
Hi, thanks for your work.
I am reproducing your results with shrink set to 1. However, I found the shrink annotations that you provide are thicker than its original ones. Is that processed with ```cv2.polylines(img, thickness=2)```  or other thickness ratio?
The following ones are my reproductions of annotation "2007_000032.xml":

Directly converted from xml of ScribbleSup:
![image (1)](https://user-images.githubusercontent.com/33063734/232741569-b01ce628-db2a-4589-9243-d1902902c5d6.png)

Converted form xml of ScribbleSup with ```thickness=2``` set in cv2.polylines():
![image (2)](https://user-images.githubusercontent.com/33063734/232741861-a5f83a6a-7233-4b86-ad30-54dbf18c69cc.png)

Shrink=0.2 provided by this repo:
![image (3)](https://user-images.githubusercontent.com/33063734/232742307-f7a434c4-c80a-41c1-81d0-34168424b1ab.png)

**Comment by panzhiyi** [comment]
We use [convertscribbles.m](https://github.com/meng-tang/rloss/blob/master/data/pascal_scribble/convertscribbles.m) to generate the scribble data.

**Comment by Zxl19990529** [comment]
OK, thank you very much.
